name: Build project and validate formatting

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 22
      uses: actions/setup-java@v2
      with:
        distribution: adopt
        java-version: 22
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4.2
      with:
        maven-version: 3.9.8
    - name: Build project
      run: mvn test -B
    - name: Validate formatting
      run: mvn validate formatter:validate
    - uses: actions/upload-artifact@v4
      with:
        name: AdvancedAchievements
        path: advanced-achievements-plugin/target/AdvancedAchievements.jar

